version: "3.3"
services:

  traefik:
    image: traefik
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false

  mastermind:
    image: mastermind
    build: ./mastermind
    depends_on:
      - mongo
    environment:
      MONGO_HOST: "mongo"
      MONGO_PORT: 27017
    labels:
      - "traefik.enable=true"
      - "traefik.backend=mastermind"
      - "traefik.http.routers.mastermind.rule=PathPrefix(`/game`)"
    networks:
      - network
    expose:
      - "80"
    command:
      gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:80 mastermind.main:app

  frontend:
    image: front_end
    build: 
      context: ./front_end/front_end
    depends_on:
        - mastermind
    labels:
      - "traefik.enable=true"
      - "traefik.backend=front_end"
      - "traefik.http.routers.front_end.rule=PathPrefix(`/`)"
    networks:
      - network
  
  mongo:
    image: mongo
    networks:
      - network
  # TODO: create second user for security

networks:
  network:
    driver: bridge
