version: "3.7"
services:

  mastermind:
    image: mastermind
    build: ./mastermind
    environment:
      MODULE_NAME: "mastermind.main"
    networks:
      - network

  frontend:
    image: front_end
    build: 
      context: ./front_end/front_end
    depends_on:
        - mastermind
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - network

networks:
  network:
    driver: bridge
