apiVersion: v1
kind: Service
metadata:
  name: {{ template "microservice.fullname" . }}
  labels:
    app: {{ template "microservice.name" . }}
    chart: {{ template "microservice.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    {{- with .Values.labels }}
      {{- toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ template "microservice.name" . }}
    release: {{ .Release.Name | quote }}
  type: {{ .Values.service.type | quote }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
