---
"""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sergiuszrokoszdxc/nice_project_nginx
        ports:
        - containerPort: 80 # TODO: configuration variable
        env:
        - name: NICE_PROJECT_PORT
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: NICE_PROJECT_PORT
        - name: NICE_PROJECT_HOST
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: NICE_PROJECT_HOST
        - name: NGINX_LISTEN_PORT
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: NGINX_LISTEN_PORT
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  NICE_PROJECT_PORT: "5001" # TODO: configuration variable
  NICE_PROJECT_HOST: "nice-project-service" # TODO: configuration variable
  NGINX_LISTEN_PORT: "80" # TODO: configuration variable
"""