apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
spec:
  chart:
    git: git@github.com:sergiuszrokoszdxc/nice_project.git
    ref: master
    path: deployment/kubernetes/microservice
  values:
    image:
      repository: sergiuszrokoszdxc/nice_project_frontend
      tag: a63831b
    dashboard:
      enabled: true
      domain: projextc.20.54.48.95.nip.io