apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: niceproject
spec:
  chart:
    git: https://containous.github.io/traefik-helm-chart
    ref: master
    path: traefik