name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  Test_and_build:
    strategy:
      matrix:
        service: [nice_project, nginx]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # get tests log out
      - name: Installing dependencies for test and build phase
        run: docker build --tag nice_project_tests --target build  nice_project
      - name: Unit and integration tests of nice_project
        run: docker run nice_project_tests python -m unittest
      - name: Building release image
        run: |
          docker-compose build
          docker-compose up -d nginx
        env:
          NGINX_LISTEN_PORT: 5002
          NICE_PROJECT_PORT: 5001
          SERVICE_PORT: 5000
      - name: Acceptance tests
        run: docker-compose up acceptance_tests
        env:
          NGINX_LISTEN_PORT: 5002
          NICE_PROJECT_PORT: 5001
          SERVICE_PORT: 5000
      - name: Tear down docker-compose
        run: docker-compose down
      - name: Tagging realease image
        run: |
          docker tag ${{ matrix.service }} "${DOCKER_USER}/nice_project_${{ matrix.service }}:latest"
          SHORT_SHA="${GITHUB_SHA:0:7}"
          echo "::set-env name=SHORT_SHA::${SHORT_SHA}"
          docker tag ${{ matrix.service }} "${DOCKER_USER}/nice_project_${{ matrix.service }}:${SHORT_SHA}"
      - name: Tagging image with a release tag
        if: ${{ github.event_name == 'release' }}
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "::set-env name=TAG::${TAG}"
          docker tag ${{ matrix.service }} ${DOCKER_USER}/nice_project_${{ matrix.service }}:${TAG}
      - name: Loging into dockerhub
        run: 
          echo "$DOCKER_PASSWORD" | docker login -u "${DOCKER_USER}" --password-stdin
      - name: Pushing images
        run: |
          docker push ${DOCKER_USER}/nice_project_${{ matrix.service }}:latest
          docker push ${DOCKER_USER}/nice_project_${{ matrix.service }}:${SHORT_SHA}
      - name: Pushing image with a release tag
        if: ${{ github.event_name == 'release' }}
        run: docker push ${DOCKER_USER}/nice_project_${{ matrix.service }}:${TAG}
      - name: Logint out of dockerhub
        run: docker logout
    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_ACCOUNT_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

