#- unit testy i integracyjny
#- dockercompose - testy akcepytacyjne

#! być może zrobić unittesty w trakcie budowania


name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  unit_and_integration_test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - name: Fail
          run: exit 11