#- dockercompose - build
#- publish obrazu

name: Continuous Deployment

on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build release image
        run: docker build --tag nice_project nice_project
      - name: Tagging realease image
      # jeśli byłoby więcej obrazów to można zastosować matrix + zmienne?
        run: |
          docker tag nice_project "$DOCKER_USER"/nice_project_nice_project:latest
          echo '::set-env name=SHORT_SHA::"${GITHUB_SHA:0:7}"'
          docker tag nice_project "$DOCKER_USER"/nice_project_nice_project:"$SHORT_SHA"
      - name: Tagging image with a release tag
        if: ${{ github.even_name == "release" }}
        run: docker tag nice_project "$DOCKER_USER"/nice_project_nice_project:"$GITHUB_REF"
      - name: Loging into dockerhub
        run: 
          echo "::add-mask::$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - name: Pushing images
        run: |
          docker push "$DOCKER_USER"/nice_project_nice_project:latest
          docker push "$DOCKER_USER"/nice_project_nice_project:"$SHORT_SHA"
      - name: Pushing image with a release tag
        if: ${{ github.even_name == "release" }}
        run: docker push "$DOCKER_USER"/nice_project_nice_project:"$GITHUB_REF"
      - name: Logint out of dockerhub
        run: docker logout
    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_ACCOUNT_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}