#- unit testy i integracyjny
#- dockercompose - testy akcepytacyjne

#! być może zrobić unittesty w trakcie budowania


name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  unit_and_integration_test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: List directories once more
          run: ls
        - name: Testy
          run: docker-compose up
          env:
            NGINX_LISTEN_PORT: 5002
            NICE_PROJECT_PORT: 5001
            SERVICE_PORT: 5000