#- unit testy i integracyjny
#- dockercompose - testy akcepytacyjne

#! być może zrobić unittesty w trakcie budowania


name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          # get tests log out
        - name: Unit and integration tests of nice_project
          run: docker build --tag nice_project_tests --target build  nice_project
        - name: EXECc
          run: docker run nice_project_tests python -m unittest
        - name: Acceptance tests
          run: docker-compose up
          env:
            NGINX_LISTEN_PORT: 5002
            NICE_PROJECT_PORT: 5001
            SERVICE_PORT: 5000