name: Continuous Deployment

on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  Release:
    strategy:
      matrix:
        service: [nice_project, nginx]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #- name: Azure Kubernetes set context
      #  uses: Azure/aks-set-context@v1
      #  with:
      #    creds: ${{ secrets.AZURE_CREDENTIALS }}
      #    resource-group: kubernetes
      #    cluster-name: kubernetes
      #- name: Deploy to Kubernetes cluster
      #  uses: Azure/k8s-deploy@v1
      #  with:
      #    manifests: | 
      #      deployment\kubernetes