#- dockercompose - build
#- publish obrazu

name: Continuous Deployment

on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  Build:
    strategy:
      service: [nice_project, nginx]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build release image
        run: |
          docker build --tag ${{ matrix.service }} ${{ matrix.service }}
      - name: Tagging realease image
      # jeśli byłoby więcej obrazów to można zastosować matrix + zmienne?
        run: |
          docker tag ${{ matrix.service }} "$DOCKER_USER"/nice_project_${{ matrix.service }}:latest
          SHORT_SHA="${GITHUB_SHA:0:7}"
          echo '::set-env name=SHORT_SHA::'"$SHORT_SHA"
          docker tag ${{ matrix.service }} "$DOCKER_USER"/nice_project_${{ matrix.service }}:"$SHORT_SHA"
      - name: Tagging image with a release tag
        if: ${{ github.event_name == 'release' }}
        run: |
          TAG="${GITHUB_REF##*/}"
          echo '::set-env name=TAG::'"$TAG"
          docker tag ${{ matrix.service }} "$DOCKER_USER"/nice_project_${{ matrix.service }}:"$TAG"
      - name: Loging into dockerhub
        run: 
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - name: Pushing images
        run: |
          docker push "$DOCKER_USER"/nice_project_${{ matrix.service }}:latest
          docker push "$DOCKER_USER"/nice_project_${{ matrix.service }}:"$SHORT_SHA"
      - name: Pushing image with a release tag
        if: ${{ github.event_name == 'release' }}
        run: |
          docker push "$DOCKER_USER"/nice_project_${{ matrix.service }}:"$TAG"
      - name: Logint out of dockerhub
        run: docker logout
    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_ACCOUNT_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}