name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  Test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # get tests log out
      - name: Installing dependencies for test and build phase
        run: docker build --tag mastermind_test --target test mastermind
      - name: Unit and integration tests of nice_project
        run: docker run mastermind_test python -m pytest
        # TODO: test frontend
      - name: Build release image for mastermind
      run: docker build --tag mastermind_release --target release mastermind
      - name: Build release image for frontend
      run: docker build --tag frontend_release --target release frontend
      # TODO: add acceptance tests
      - name: Tag release images
      run: |
        SHORT_SHA="${GITHUB_SHA:0:7}"
        echo "::set-env name=SHORT_SHA::${SHORT_SHA}"
        docker tag mastermind_release ${DOCKER_USER}/nice_project_mastermind:latest
        docker tag mastermind_release ${DOCKER_USER}/nice_project_mastermind:${SHORT_SHA}
        docker tag frontend_release ${DOCKER_USER}/nice_project_frontend:latest
        docker tag frontend_release ${DOCKER_USER}/nice_project_frontend:${SHORT_SHA}
      - name: Loging into dockerhub
        run: 
          echo "$DOCKER_PASSWORD" | docker login -u "${DOCKER_USER}" --password-stdin
      - name: Push release images
        run: |
          docker push ${DOCKER_USER}/nice_project_mastermind:latest
          docker push ${DOCKER_USER}/nice_project_frontend:latest
          docker push ${DOCKER_USER}/nice_project_mastermind:${SHORT_SHA}
          docker push ${DOCKER_USER}/nice_project_frontend:${SHORT_SHA}
      - name: Logint out of dockerhub
        run: docker logout
    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_ACCOUNT_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}