name: Continuous Deployment

on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  Release:
    #strategy:
    #  matrix:
    #    service: [nice_project, nginx]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: >
            az deployment group create
            -n compApp
            --resource-group ComplimentApp
            -m Incremental
            -f deployment/azure/template.json
            -p @deployment/azure/parameters.json
