#- dockercompose - build
#- publish obrazu

name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:
        - name: Hello
          run: echo "Hello"